const data = {
  products: [
    {
      name: "Cargo Pants Bape",
      display: "cargo~pants~bape",
      category: "Pants",
      image: `images/jeans.jpg`,
      price: 120,
      counInStock: 12,
      brand: "Bape",
      raing: 4.5,
      numReview: 10,
      description: "High Quality Paint",
    },
    {
      name: "Short Jean Nike",
      display: "short~jean~nike",
      category: "Shoes",
      image: `images/jeans.jpg`,
      price: 120,
      counInStock: 12,
      brand: "Nike",
      raing: 4.5,
      numReview: 10,
      description: "Suitable for everyone",
    },
    {
      name: "Black Wag Hoodies Champion",
      display: "hoodie~champion",
      category: "Hoodies",
      image: `images/jeans.jpg`,
      price: 120,
      counInStock: 12,
      brand: "Champion",
      raing: 4.5,
      numReview: 10,
      description: "A lot of people use it",
    },
    {
      name: "Blue Denim Jacket",
      display: "denim~jacket",
      category: "Jacket",
      image: `images/jeans.jpg`,
      price: 120,
      counInStock: 12,
      brand: "Bape",
      raing: 4.5,
      numReview: 10,
      description: "High Quality Pants",
    },
  ],
};
export default data;
