const data = {
  products: [
    {
      name: "Cargo Pants Bape",
      display: "cargo~pants~bape",
      category: "Pants",
      image: "/images/anh1.jpg",
      price: 120,
      counInStock: 0,
      brand: "Bape",
      rating: 5,
      numReviews: 10,
      description: "High Quality Paint",
    },
    {
      name: "Short Jean Nike",
      display: "short~jean~nike",
      category: "Shoes",
      image: "/images/bomber.jpg",
      price: 120,
      counInStock: 12,
      brand: "Nike",
      rating: 4,
      numReviews: 106,
      description: "Suitable for everyone",
    },
    {
      name: "Black Hoodies Champion",
      display: "hoodie~champion",
      category: "Hoodies",
      image: "/images/anh2.jpg",
      price: 120,
      counInStock: 12,
      brand: "Champion",
      rating: 2.5,
      numReviews: 9,
      description: "A lot of people use it",
    },
    {
      name: "Blue Denim Jacket",
      display: "denim~jacket",
      category: "Jacket",
      image: "/images/anh3.jpg",
      price: 120,
      counInStock: 12,
      brand: "Bape",
      rating: 3,
      numReviews: 16,
      description: "High Quality Pants",
    },
  ],
};
export default data;
